language: node_js
node_js:
  - "stable"
  - "4"
  - "0.12"
  - "0.10"

# Install grunt-cli globally before installing all dependencies, including grunt
before_install:
  - npm install grunt-cli -g

# Allow travis to start Firefox for automated testing
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start